---
title: "netClust"
output: rmarkdown::html_vignette
description: >
  Network-based clustering of binary data. Optional adjustment for covariates. 
vignette: >
  %\VignetteIndexEntry{netClust}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(devtools)
load_all()
library(netClust)
```


### Demonstration:
Simulate binary data and learn clusters subsequently.

```{r, eval = FALSE}
# Simulate binary data
k_clust <- 3
ss <- c(400, 500, 600) # samples in each cluster
simulation_data <- netClust::sampleData(k_clust = k_clust, n_vars = 20, n_samples = ss)

sampled_data <- simulation_data$sampled_data

# Network-based clustering
cluster_res_t <- get_clusters(sampled_data, k_clust = k_clust)

library(mclust)
cluster_res_t <- get_clusters(sampled_data, k_clust = k_clust, categorical = TRUE)

# cluster_res_t <- get_clusters(sampled_data, k_clust = k_clust,
#                               newallrelativeprobabs = cluster_res_t$newallrelativeprobabs, categorical=FALSE)

library(mclust)
adjustedRandIndex(simulation_data$cluster_membership, cluster_res_t$clustermembership)

# Bernoulli mixture models 
test_res <- BBMMclusterEM(sampled_data, 0.5, 3, nIterations = 10, verbose=TRUE)
adjustedRandIndex(simulation_data$cluster_membership, test_res$newclustermembership)

test_res <- BMMclusterEM(sampled_data, 0.5, 3, nIterations = 10, verbose=TRUE)
adjustedRandIndex(simulation_data$cluster_membership, test_res$newclustermembership)


# cluster_res_t <- get_clusters(sampled_data, k_clust = k_clust, 
#                               newallrelativeprobabs = cluster_res_t$newallrelativeprobabs, categorical=TRUE)
# 
# adjustedRandIndex(simulation_data$cluster_membership, cluster_res_t$clustermembership)
# 
# adjustedRandIndex(simulation_data$cluster_membership, cluster_res_t$clustermembership)
# 
# 
# res_kmeans1 <- kmeans(sampled_data, k_clust)
# adjustedRandIndex(simulation_data$cluster_membership, res_kmeans1$cluster)
# 
# aa <- mclust::Mclust(sampled_data, k_clust)
# adjustedRandIndex(simulation_data$cluster_membership, aa$classification)
# 
# res_BBMM2 <- BBMMclusterEM(sampled_data, chi = 0.5, k_clust = 5, startseed = 1 * 100, nIterations = 10, verbose = TRUE)
# adjustedRandIndex(simulation_data$cluster_membership, res_BBMM2$newclustermembership)


# alternatives:
# cluster_res <- netCluster(my_data, kclust = 3)
# cluster_res_test <- netClustParallel(my_data, kclust = 3)
# cluster_res_p <- netClusterParallel(my_data, kclust = 3)
```
